language: rust

os:
- osx

rust:
- nightly

cache: cargo

addons:
  homebrew:
    packages:
    - glib
    - libffi
    - gnutls
    - gstreamer
    - gst-plugins-base
    - gst-libav
    - gst-plugins-bad
    - gst-plugins-good
    - gst-plugins-ugly
    - gst-rtsp-server
    - gst-editing-services

install:
  - export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig:$PKG_CONFIG_PATH
  - export PKG_CONFIG_PATH=/usr/local/opt/glib/lib/pkgconfig:$PKG_CONFIG_PATH

branches:
  only:
  - master

script:
- cargo build --release
