language: rust

os:
- osx

rust:
- nightly

cache: cargo

addons:
  homebrew:
    packages:
    - glib
    - libffi
    - gnutls
    - gstreamer
    - gst-plugins-base
    - gst-libav
    - gst-plugins-bad
    - gst-plugins-good
    - gst-plugins-ugly
    - gst-rtsp-server
    - gst-editing-services

branches:
  only:
  - master

script:
- cargo build --release
